# Public headers.
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

is_windows = ($c.target.class == 'windows')
is_posix = (!$is_windows)

use_mbedtls = ($config.libnng.tls_engine == 'mbedtls')
use_wolfssl = ($config.libnng.tls_engine == 'wolfssl')
use_supp_tls = ($config.libnng.supp_tls && ($use_mbedtls || $use_wolfssl))

if ($use_mbedtls || $use_wolfssl)
{
    fail 'TLS is currently not supported'
}

lib{nng}: $pub/{$pub_hdrs}
lib{nng}: c{*}
lib{nng}: {h c}{compat/** -compat/**_test}
lib{nng}: {h c}{core/* -core/*_test}
lib{nng}: {h c}{platform/windows/*}: include = $is_windows
lib{nng}: {h c}{platform/posix/*}: include = $is_posix
lib{nng}: {h c}{sp/transport}

# protocol compilation
lib{nng}: c{sp/protocol/bus0/bus}: include = $config.libnng.proto_bus0
lib{nng}: c{sp/protocol/pair0/pair}: include = $config.libnng.proto_pair0
lib{nng}: c{sp/protocol/pair1/pair sp/protocol/pair1/pair1_poly}: include = $config.libnng.proto_pair1
lib{nng}: c{sp/protocol/pipeline0/pull}: include = $config.libnng.proto_pull0
lib{nng}: c{sp/protocol/pipeline0/push}: include = $config.libnng.proto_push0
lib{nng}: c{sp/protocol/pubsub0/pub}: include = $config.libnng.proto_pub0
lib{nng}: c{sp/protocol/pubsub0/sub sp/protocol/pubsub0/xsub}: include = $config.libnng.proto_sub0
lib{nng}: c{sp/protocol/reqrep0/req sp/protocol/reqrep0/xreq}: include = $config.libnng.proto_req0
lib{nng}: c{sp/protocol/reqrep0/rep sp/protocol/reqrep0/xrep}: include = $config.libnng.proto_rep0
lib{nng}: c{sp/protocol/survey0/survey sp/protocol/survey0/xsurvey}: include = $config.libnng.proto_surveyor0
lib{nng}: c{sp/protocol/survey0/respond sp/protocol/survey0/xrespond}: include = $config.libnng.proto_respondent0

# transport compilation
lib{nng}: c{sp/transport/inproc/inproc}: include = $config.libnng.transport_inproc
lib{nng}: c{sp/transport/ipc/ipc}: include = $config.libnng.transport_ipc
lib{nng}: c{sp/transport/tcp/tcp}: include = $config.libnng.transport_tcp
lib{nng}: c{sp/transport/tls/tls}: include = $config.libnng.transport_tls
lib{nng}: c{sp/transport/ws/websocket}: include = $config.libnng.transport_ws

# supplemental compilation
lib{nng}: {h c}{supplemental/base64/base64}: include = $config.libnng.supp_base64
lib{nng}: c{supplemental/http/http_public} h{supplemental/http/http_api}
lib{nng}: c{supplemental/http/* -supplemental/http/http_public}: include = $config.libnng.supp_http
lib{nng}: {h c}{supplemental/sha1/sha1}: include = $config.libnng.supp_sha1
lib{nng}: h{supplemental/tls/tls_api} c{supplemental/tls/tls_common}
lib{nng}: c{supplemental/util/*}
lib{nng}: {h c}{supplemental/tls/mbedtls/*}: include = ($config.libnng.supp_tls && $use_mbedtls)
lib{nng}: {h c}{supplemental/websocket/websocket}: include = $config.libnng.supp_websocket
lib{nng}: c{supplemental/websocket/stub}: include = (!$config.libnng.supp_websocket)


# testing lib can only be used with static linkage
liba{nng_testing}: {h c}{testing/*}
liba{nng_testing}: c{compat/**_test}
liba{nng_testing}: c{core/*_test}
liba{nng_testing}: c{platform/*_test}

liba{nng_testing}: c{sp/protocol/bus0/*_test}: include = $config.libnng.proto_bus0
liba{nng_testing}: c{sp/protocol/pair0/*_test}: include = $config.libnng.proto_pair0
liba{nng_testing}: c{sp/protocol/pair1/*_test}: include = $config.libnng.proto_pair1
liba{nng_testing}: c{sp/protocol/pipeline0/pull_test}: include = $config.libnng.proto_pull0
liba{nng_testing}: c{sp/protocol/pipeline0/push_test}: include = $config.libnng.proto_push0
liba{nng_testing}: c{sp/protocol/pubsub0/pub_test}: include = $config.libnng.proto_pub0
liba{nng_testing}: c{sp/protocol/pubsub0/sub_test sp/protocol/pubsub0/xsub_test}: include = $config.libnng.proto_sub0
liba{nng_testing}: c{sp/protocol/reqrep0/req_test sp/protocol/reqrep0/xreq_test}: include = $config.libnng.proto_req0
liba{nng_testing}: c{sp/protocol/reqrep0/rep_test sp/protocol/reqrep0/xrep_test}: include = $config.libnng.proto_rep0
liba{nng_testing}: c{sp/protocol/survey0/survey_test sp/protocol/survey0/xsurvey_test}: include = $config.libnng.proto_surveyor0
liba{nng_testing}: c{sp/protocol/survey0/respond_test sp/protocol/survey0/xrespond_test}: include = $config.libnng.proto_respondent0

liba{nng_testing}: c{sp/transport/ipc/ipc_test}: include = $config.libnng.transport_ipc
liba{nng_testing}: c{sp/transport/tcp/tcp_test}: include = $config.libnng.transport_tcp
liba{nng_testing}: c{sp/transport/ws/ws_test}: include = $config.libnng.transport_ws

liba{nng_testing}: c{supplemental/base64/base64_test}: include = $config.libnng.supp_base64
liba{nng_testing}: c{supplemental/sha1/sha1_test}: include = $config.libnng.supp_sha1
liba{nng_testing}: c{supplemental/tls/tls_test}
liba{nng_testing}: c{supplemental/websocket/*_test}: include = $config.libnng.supp_websocket
liba{nng_testing}: liba{nng}

config_flags = $config.libnng.proto_bus0 \
    $config.libnng.proto_pair0 \
    $config.libnng.proto_pair1 \
    $config.libnng.proto_pull0 \
    $config.libnng.proto_push0 \
    $config.libnng.proto_pub0 \
    $config.libnng.proto_sub0 \
    $config.libnng.proto_req0 \
    $config.libnng.proto_rep0 \
    $config.libnng.proto_surveyor0 \
    $config.libnng.proto_respondent0 \
    $config.libnng.transport_inproc \
    $config.libnng.transport_ipc \
    $config.libnng.transport_tcp \
    $config.libnng.transport_tls \
    $config.libnng.transport_ws \
    $config.libnng.supp_http \
    $use_supp_tls \
    ($config.libnng.supp_tls && $use_mbedtls) \
    ($config.libnng.supp_tls && $use_mbedtls) \
    ($config.libnng.supp_tls && $use_wolfssl) \
    ($config.libnng.supp_tls && $use_wolfssl)


config_poptions = NNG_HAVE_BUS0 \
    NNG_HAVE_PAIR0 \
    NNG_HAVE_PAIR1 \
    NNG_HAVE_PULL0 \
    NNG_HAVE_PUSH0 \
    NNG_HAVE_PUB0 \
    NNG_HAVE_SUB0 \
    NNG_HAVE_REQ0 \
    NNG_HAVE_REP0 \
    NNG_HAVE_SURVEYOR0 \
    NNG_HAVE_RESPONDENT0 \
    NNG_TRANSPORT_INPROC \
    NNG_TRANSPORT_IPC \
    NNG_TRANSPORT_TCP \
    NNG_TRANSPORT_TLS \
    NNG_TRANSPORT_WS \
    NNG_SUPP_HTTP \
    NNG_SUPP_TLS \
    NNG_TLS_ENGINE_INIT=nng_tls_engine_init_mbed \
    NNG_TLS_ENGINE_INIT=nng_tls_engine_init_mbed \
    NNG_TLS_ENGINE_INIT=nng_tls_engine_init_wolf \
    NNG_TLS_ENGINE_INIT=nng_tls_engine_init_wolf

nng_impl_poptions =
for i: $integer_sequence(0, $size($config_poptions))
{
    flag = ($config_flags[$i])
    opt = ($config_poptions[$i])
    if $flag
    {
        nng_impl_poptions += -D$opt
    }
}

config_flags = $config.libnng.elide_deprecated \
    $config.libnng.set_stacksize \
    $config.libnng.enable_stats \
    ($config.libnng.resolve_concurrency != [null]) \
    ($config.libnng.num_taskq_threads != [null])

config_poptions = NNG_ELIDE_DEPRECATED \
    NNG_SETSTACKSIZE \
    NNG_ENABLE_STATS \
    NNG_RESOLV_CONCURRENCY=$config.libnng.resolve_concurrency \
    NNG_NUM_TASKQ_THREADS=$config.libnng.num_taskq_threads

for i: $integer_sequence(0, $size($config_poptions))
{
    flag = ($config_flags[$i])
    opt = ($config_poptions[$i])
    if $flag
    {
        c.poptions += -D$opt
    }
}

c.poptions += -DNNG_MAX_TASKQ_THREADS=$config.libnng.max_taskq_threads

platform_poptions = # Platform specific poptions.
platform_libs = # Platform specific libraries.
switch $c.target.class
{
    case 'windows'
    {
        if ($cxx.target.system == 'mingw32')
            platform_libs += -lws2_32 -lmswsock -ladvapi32
        else
            platform_libs += ws2_32.lib mswsock.lib advapi32.lib

        platform_poptions += -D_WIN32_WINNT=0x0600 -D_CRT_SECURE_NO_WARNINGS -D_CRT_RAND_S
        nng_impl_poptions += -DNNG_PLATFORM_WINDOWS
    }
    case 'linux'
    {
        nng_impl_poptions += -DNNG_PLATFORM_POSIX -DNNG_PLATFORM_LINUX -DNNG_USE_EVENTFD -DNNG_HAVE_ABSTRACT_SOCKETS
    }
    case 'freebsd'
    {
        nng_impl_poptions += -DNNG_PLATFORM_POSIX -DNNG_PLATFORM_FREEBSD
    }
    case 'netbsd'
    {
        nng_impl_poptions += -DNNG_PLATFORM_POSIX -DNNG_PLATFORM_NETBSD
    }
    case 'openbsd'
    {
        nng_impl_poptions += -DNNG_PLATFORM_POSIX -DNNG_PLATFORM_OPENBSD
    }
    case 'macos'
    {
        nng_impl_poptions += -DNNG_PLATFORM_POSIX -DNNG_PLATFORM_DARWIN
    }
    default
    {
        # hope for POSIX
        warn "This platform may not be supported: $c.target.class"
        nng_impl_poptions +=  -DNNG_PLATFORM_POSIX
    }
}

if $is_posix
{
    platform_poptions += -D_GNU_SOURCE -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS
    platform_libs += -pthread
}

# Build options.
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/
out_pfx_tst = [dir_path] $out_root/src/testing/
src_pfx_tst = [dir_path] $src_root/src/testing/

testing_intf_poptions =  "-I$out_pfx_tst" "-I$src_pfx_tst" -DNNG_TEST_LIB -DNNG_PRIVATE $nng_impl_poptions

c.poptions += "-I$out_pfx_src" "-I$src_pfx_src" \
              "-I$out_pfx_inc" "-I$src_pfx_inc" \
              "-I$out_pfx_tst" "-I$src_pfx_tst" \
              $platform_poptions \
              $nng_impl_poptions
c.libs += $platform_libs

{hbmia obja}{*}: c.poptions += -DNNG_STATIC_LIB
{hbmis objs}{*}: c.poptions += -DNNG_SHARED_LIB

# Export options.
lib{nng}:
{
  c.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  c.export.libs = $platform_libs
}

liba{nng}: c.export.poptions += -DNNG_STATIC_LIB

lib{nng_testing}:
{
  c.poptions = $testing_intf_poptions
  c.export.poptions = "-I$out_pfx_src" "-I$src_pfx_src" $testing_intf_poptions
  c.export.libs = lib{nng}
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
{
  lib{nng nng_testing}: bin.lib.version = "-$version.project_id"
}
else
{
  lib{nng nng_testing}: bin.lib.version = "-$version.major.$version.minor"
}

# Don't install private headers.
h{*}: install = false
