
import impl_libs = libnng%liba{nng_testing}

test_files = c{bus \
    device \
    files \
    httpclient \
    httpserver \
    inproc \
    ipc \
    ipcsupp \
    ipcwinsec \
    multistress \
    nonblock \
    options \
    pipe \
    pollfd \
    reqctx \
    reqstress \
    scalability \
    stats \
    synch \
    tcpsupp \
    tcp \
    tcp6 \
    udp \
    ws}

for file: $test_files
{
    test_name = $name($file)_test
    exe{$test_name}: $file {h c}{convey} h{stubs}
    exe{$test_name}: $impl_libs
    exe{$test_name}: test.options = -v
    exe{$test_name}: test.timeout = /10
    ./: exe{$test_name}
}
